### ISSUE TITLE
Default dark theme makes search bar badly visible

### ISSUE THREAD

**Issue by Lucy-dot-dot** [WillKirkmanM/music#113]
![grafik](https://github.com/user-attachments/assets/57a437e5-4aa4-4234-ab11-61e5a710b9b0)

OS: Windows 11
Browser: Firefox 130 / Edge / Vivaldi

After setting up the server, with no content, the displayed search bar has a very low visibility in the default dark theme (selected by the browser).

It may be preferable to no have the linear gradient there or make the search bar in a different color to promote the bar better

**Comment by WillKirkmanM** [comment]
Hello @Lucy-dot-dot, thank you for using Music & thank you for bringing this to my attention,

The colour for the top gradient is set and found in the `GradientHoverProvider.tsx`, initially it is #CBC3E3 or the pastel purple colour found.

![images](https://github.com/user-attachments/assets/81bc4fc3-a900-4af0-b587-ba9a88d44442)

https://github.com/WillKirkmanM/music/blob/f6dcbefe4802caabad8123cba5638d6c07e7514b/apps/web/components/Providers/GradientHoverProvider.tsx#L13

Part of the reason for the badly visible searchbar and the profile picture in this state is that it is meant to be visible when you scroll down from the page, for example:

![image](https://github.com/user-attachments/assets/85655efa-84ed-4ca3-8a64-8530814817a4)

The behaviour that governs this is found through the `ScrollContext` in `ScrollProvider.tsx`

https://github.com/WillKirkmanM/music/blob/f6dcbefe4802caabad8123cba5638d6c07e7514b/apps/web/components/Providers/ScrollProvider.tsx

Which is used in the `NavBar`:

https://github.com/WillKirkmanM/music/blob/f6dcbefe4802caabad8123cba5638d6c07e7514b/apps/web/components/Layout/Navbar.tsx#L13

I believe this is intended as it should look YouTube Music esque:

![image](https://github.com/user-attachments/assets/59fde45b-1d78-4bf0-bacc-d7d82cbf920f)

I do appreciate this as the first issue! 🎉🍾

Thank you,
– WillKirkmanM

**Comment by WillKirkmanM** [comment]
It is definitely in the realm of possibility, it also want to do what Spotify has done well with their gradients, which is actually where the idea came from:
![image](https://github.com/user-attachments/assets/eceee43f-9f3a-4b7c-9615-adab1d1d98b3)

Where the gradient matches the gradient for the cover art of the Album "Aaliyah".
